### ISSUE TITLE
Update Nice-DCV to 2023.1-16388

### ISSUE THREAD

**Issue by davdunc** [Internethamster/build-cloud-kde-ansible#3]
https://docs.aws.amazon.com/dcv/latest/adminguide/doc-history-release-notes.html#dcv-2023-1-16388mar

The most recent version to include updates for the Linux client is DCV 2023.1-16388 from December 19, 2023, but there is no reason not to move to latest that I can identify.

**Comment by Conan-Kudo** [comment]
We're still in a situation where Wayland is not supported, it seems... Since F40 we're Wayland-only, this is no bueno. 😞

**Comment by Conan-Kudo** [comment]
So we've started down the path for nesting in Weston for now, so I'm closing this.
